import type { UserWithSocials, Project, BadgeLevel } from "@/lib/types/database";

function generateHeatmapData(): Record<string, number> {
  const data: Record<string, number> = {};
  const today = new Date();
  for (let i = 0; i < 365; i++) {
    const date = new Date(today);
    date.setDate(date.getDate() - i);
    const key = date.toISOString().split("T")[0];
    // Random activity: ~60% chance of activity
    if (Math.random() > 0.4) {
      data[key] = Math.floor(Math.random() * 4) + 1;
    }
  }
  return data;
}

const mockProjects: Project[] = [
  {
    id: "p1",
    user_id: "u1",
    title: "AI Chat Dashboard",
    description: "Real-time AI chat interface with streaming responses, built in a weekend vibe coding session.",
    tech_stack: ["Next.js", "TypeScript", "OpenAI", "Tailwind"],
    live_url: "https://aichat.demo.com",
    github_url: "https://github.com/demo/aichat",
    image_url: null,
    build_time: "2 days",
    tags: ["AI", "SaaS", "Dashboard"],
    created_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "p2",
    user_id: "u1",
    title: "Crypto Portfolio Tracker",
    description: "Track your crypto portfolio with real-time prices and beautiful charts.",
    tech_stack: ["React", "Node.js", "CoinGecko API", "Chart.js"],
    live_url: "https://crypto.demo.com",
    github_url: "https://github.com/demo/crypto",
    image_url: null,
    build_time: "3 days",
    tags: ["Crypto", "Finance", "Dashboard"],
    created_at: "2026-01-20T00:00:00Z",
  },
  {
    id: "p3",
    user_id: "u2",
    title: "Dev Blog Platform",
    description: "Markdown-powered blog with syntax highlighting and SEO optimization.",
    tech_stack: ["Next.js", "MDX", "Tailwind"],
    live_url: "https://blog.demo.com",
    github_url: "https://github.com/demo/blog",
    image_url: null,
    build_time: "1 day",
    tags: ["Blog", "Content", "Developer Tools"],
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "p4",
    user_id: "u3",
    title: "Task Automation Bot",
    description: "Telegram bot that automates daily tasks and sends reminders using AI.",
    tech_stack: ["Python", "Telegram API", "GPT-4", "Redis"],
    live_url: null,
    github_url: "https://github.com/demo/taskbot",
    image_url: null,
    build_time: "4 days",
    tags: ["AI", "Automation", "Bot"],
    created_at: "2026-02-28T00:00:00Z",
  },
  {
    id: "p5",
    user_id: "u4",
    title: "NFT Marketplace",
    description: "Minimal NFT marketplace with wallet connection and minting.",
    tech_stack: ["Next.js", "Solidity", "Ethers.js", "IPFS"],
    live_url: "https://nft.demo.com",
    github_url: "https://github.com/demo/nftmarket",
    image_url: null,
    build_time: "5 days",
    tags: ["Web3", "NFT", "Marketplace"],
    created_at: "2026-01-10T00:00:00Z",
  },
  {
    id: "p6",
    user_id: "u7",
    title: "FitTrack Mobile App",
    description: "Cross-platform fitness tracker with workout logging, progress photos, and social challenges.",
    tech_stack: ["React Native", "Expo", "Firebase", "TypeScript"],
    live_url: "https://fittrack.demo.com",
    github_url: "https://github.com/demo/fittrack",
    image_url: null,
    build_time: "6 days",
    tags: ["Mobile", "Health", "Social"],
    created_at: "2026-02-10T00:00:00Z",
  },
  {
    id: "p7",
    user_id: "u8",
    title: "Kubernetes Cluster Dashboard",
    description: "Real-time monitoring dashboard for K8s clusters with auto-scaling alerts and resource visualization.",
    tech_stack: ["Go", "Docker", "Kubernetes", "Prometheus", "Grafana"],
    live_url: null,
    github_url: "https://github.com/demo/k8s-dash",
    image_url: null,
    build_time: "7 days",
    tags: ["DevOps", "Infrastructure", "Monitoring"],
    created_at: "2026-01-25T00:00:00Z",
  },
  {
    id: "p8",
    user_id: "u9",
    title: "Design System Playground",
    description: "Interactive component playground with live Figma sync, theme switching, and CSS variable editor.",
    tech_stack: ["Framer Motion", "Tailwind", "Radix UI", "Storybook"],
    live_url: "https://designsys.demo.com",
    github_url: "https://github.com/demo/designsys",
    image_url: null,
    build_time: "3 days",
    tags: ["Design", "UI/UX", "Developer Tools"],
    created_at: "2026-03-05T00:00:00Z",
  },
  {
    id: "p9",
    user_id: "u10",
    title: "Sentiment Analysis Pipeline",
    description: "End-to-end ML pipeline for social media sentiment analysis with real-time dashboards.",
    tech_stack: ["Python", "TensorFlow", "Pandas", "FastAPI", "Redis"],
    live_url: null,
    github_url: "https://github.com/demo/sentiment-ml",
    image_url: null,
    build_time: "10 days",
    tags: ["AI", "ML", "Data Engineering"],
    created_at: "2026-02-20T00:00:00Z",
  },
  {
    id: "p10",
    user_id: "u11",
    title: "Dungeon Crawler WebGL",
    description: "Procedurally generated dungeon crawler running in the browser with multiplayer support.",
    tech_stack: ["Unity", "C#", "WebGL", "Photon Networking"],
    live_url: "https://dungeoncrawl.demo.com",
    github_url: "https://github.com/demo/dungeoncrawl",
    image_url: null,
    build_time: "14 days",
    tags: ["Game Dev", "WebGL", "Multiplayer"],
    created_at: "2026-01-05T00:00:00Z",
  },
  {
    id: "p11",
    user_id: "u12",
    title: "High-Perf Message Queue",
    description: "Lock-free message queue written in Rust with PostgreSQL persistence and gRPC interface.",
    tech_stack: ["Rust", "PostgreSQL", "gRPC", "Tokio"],
    live_url: null,
    github_url: "https://github.com/demo/rustmq",
    image_url: null,
    build_time: "12 days",
    tags: ["Backend", "Systems", "Performance"],
    created_at: "2026-03-10T00:00:00Z",
  },
];

export const mockUsers: UserWithSocials[] = [
  {
    id: "u1",
    username: "vibemaster",
    email: "vibemaster@demo.com",
    bio: "Full-stack vibecoder shipping products daily. I turn ideas into deployed apps before my coffee gets cold.",
    avatar_url: null,
    streak: 127,
    longest_streak: 127,
    vibe_score: 324,
    badge_level: "silver" as BadgeLevel,
    created_at: "2025-10-01T00:00:00Z",
    social_links: {
      id: "s1",
      user_id: "u1",
      twitter: "vibemaster",
      telegram: "vibemaster",
      github: "vibemaster",
      website: "https://vibemaster.dev",
      farcaster: "vibemaster",
    },
    projects: [mockProjects[0], mockProjects[1]],
  },
  {
    id: "u2",
    username: "shipfast_dev",
    email: "ship@demo.com",
    bio: "Building in public. 90-day streak and counting. React + Node specialist.",
    avatar_url: null,
    streak: 94,
    longest_streak: 94,
    vibe_score: 238,
    badge_level: "silver" as BadgeLevel,
    created_at: "2025-11-15T00:00:00Z",
    social_links: {
      id: "s2",
      user_id: "u2",
      twitter: "shipfast_dev",
      telegram: null,
      github: "shipfast",
      website: "https://shipfast.dev",
      farcaster: null,
    },
    projects: [mockProjects[2]],
  },
  {
    id: "u3",
    username: "code_ninja",
    email: "ninja@demo.com",
    bio: "Python & AI enthusiast. Automating everything one bot at a time.",
    avatar_url: null,
    streak: 45,
    longest_streak: 62,
    vibe_score: 155,
    badge_level: "bronze" as BadgeLevel,
    created_at: "2025-12-01T00:00:00Z",
    social_links: {
      id: "s3",
      user_id: "u3",
      twitter: "codeninja",
      telegram: "codeninja",
      github: "codeninja",
      website: null,
      farcaster: null,
    },
    projects: [mockProjects[3]],
  },
  {
    id: "u4",
    username: "web3_builder",
    email: "web3@demo.com",
    bio: "Solidity dev gone full-stack. Building the decentralized future, one vibe at a time.",
    avatar_url: null,
    streak: 210,
    longest_streak: 210,
    vibe_score: 490,
    badge_level: "gold" as BadgeLevel,
    created_at: "2025-08-15T00:00:00Z",
    social_links: {
      id: "s4",
      user_id: "u4",
      twitter: "web3builder",
      telegram: null,
      github: "web3builder",
      website: "https://web3builder.xyz",
      farcaster: "web3builder",
    },
    projects: [mockProjects[4]],
  },
  {
    id: "u5",
    username: "indie_hacker",
    email: "indie@demo.com",
    bio: "Solo founder building micro-SaaS products. Shipped 12 projects in 6 months.",
    avatar_url: null,
    streak: 380,
    longest_streak: 380,
    vibe_score: 870,
    badge_level: "diamond" as BadgeLevel,
    created_at: "2025-03-01T00:00:00Z",
    social_links: {
      id: "s5",
      user_id: "u5",
      twitter: "indiehacker",
      telegram: "indiehacker",
      github: "indiehacker",
      website: "https://indiehacker.com",
      farcaster: null,
    },
    projects: mockProjects.slice(0, 3),
  },
  {
    id: "u6",
    username: "midnight_coder",
    email: "midnight@demo.com",
    bio: "I code after midnight. Dark mode is not a preference, it's a lifestyle.",
    avatar_url: null,
    streak: 15,
    longest_streak: 28,
    vibe_score: 80,
    badge_level: "none" as BadgeLevel,
    created_at: "2026-01-15T00:00:00Z",
    social_links: {
      id: "s6",
      user_id: "u6",
      twitter: "midnightcoder",
      telegram: null,
      github: "midnightcoder",
      website: null,
      farcaster: null,
    },
    projects: [mockProjects[0]],
  },
  {
    id: "u7",
    username: "mobile_mira",
    email: "mira@demo.com",
    bio: "Mobile-first developer. React Native by day, Flutter experiments by night. 30+ apps on the stores.",
    avatar_url: null,
    streak: 68,
    longest_streak: 112,
    vibe_score: 195,
    badge_level: "bronze" as BadgeLevel,
    created_at: "2025-09-20T00:00:00Z",
    social_links: {
      id: "s7",
      user_id: "u7",
      twitter: "mobile_mira",
      telegram: "mobilemira",
      github: "mobilemira",
      website: "https://mobilemira.dev",
      farcaster: null,
    },
    projects: [mockProjects[5]],
  },
  {
    id: "u8",
    username: "infra_ivan",
    email: "ivan@demo.com",
    bio: "DevOps engineer who treats infrastructure as code. If it's not in a container, it doesn't exist.",
    avatar_url: null,
    streak: 302,
    longest_streak: 302,
    vibe_score: 710,
    badge_level: "gold" as BadgeLevel,
    created_at: "2025-05-10T00:00:00Z",
    social_links: {
      id: "s8",
      user_id: "u8",
      twitter: null,
      telegram: "infraivan",
      github: "infraivan",
      website: null,
      farcaster: null,
    },
    projects: [mockProjects[6]],
  },
  {
    id: "u9",
    username: "pixel_priya",
    email: "priya@demo.com",
    bio: "Designer who codes. Bridging the gap between Figma and production with pixel-perfect components.",
    avatar_url: null,
    streak: 22,
    longest_streak: 45,
    vibe_score: 118,
    badge_level: "none" as BadgeLevel,
    created_at: "2026-01-02T00:00:00Z",
    social_links: {
      id: "s9",
      user_id: "u9",
      twitter: "pixelpriya",
      telegram: null,
      github: "pixelpriya",
      website: "https://pixelpriya.design",
      farcaster: "pixelpriya",
    },
    projects: [mockProjects[7]],
  },
  {
    id: "u10",
    username: "data_diego",
    email: "diego@demo.com",
    bio: "ML engineer turning messy data into production models. Python, TensorFlow, and too many Jupyter notebooks.",
    avatar_url: null,
    streak: 156,
    longest_streak: 180,
    vibe_score: 410,
    badge_level: "silver" as BadgeLevel,
    created_at: "2025-07-01T00:00:00Z",
    social_links: {
      id: "s10",
      user_id: "u10",
      twitter: "datadiego",
      telegram: "datadiego",
      github: "datadiego",
      website: null,
      farcaster: null,
    },
    projects: [mockProjects[8]],
  },
  {
    id: "u11",
    username: "gamedev_grace",
    email: "grace@demo.com",
    bio: "Unity developer and creative coder. Making games that run everywhere, even in your browser.",
    avatar_url: null,
    streak: 8,
    longest_streak: 35,
    vibe_score: 62,
    badge_level: "none" as BadgeLevel,
    created_at: "2026-02-01T00:00:00Z",
    social_links: {
      id: "s11",
      user_id: "u11",
      twitter: "gamedevgrace",
      telegram: null,
      github: "gamedevgrace",
      website: "https://gamedevgrace.itch.io",
      farcaster: null,
    },
    projects: [mockProjects[9]],
  },
  {
    id: "u12",
    username: "rust_renzo",
    email: "renzo@demo.com",
    bio: "Systems programmer obsessed with performance. Rust and Go for backends, PostgreSQL for everything else.",
    avatar_url: null,
    streak: 245,
    longest_streak: 245,
    vibe_score: 580,
    badge_level: "gold" as BadgeLevel,
    created_at: "2025-06-15T00:00:00Z",
    social_links: {
      id: "s12",
      user_id: "u12",
      twitter: null,
      telegram: "rustrenzo",
      github: "rustrenzo",
      website: "https://renzo.systems",
      farcaster: "rustrenzo",
    },
    projects: [mockProjects[10]],
  },
];

export { mockProjects, generateHeatmapData };
