/**
 * Custom Cloudflare Worker entrypoint for VibeTalent.
 *
 * Wraps the OpenNext-generated worker (`.open-next/worker.js`, produced by
 * `opennextjs-cloudflare build`) to add Cloudflare Cron Trigger support via a
 * `scheduled()` handler, while preserving OpenNext's `fetch` handler and
 * re-exporting its Durable Object classes (which must be exported from the
 * Worker's main module).
 *
 * The cron schedules themselves live in wrangler.jsonc and are enabled at DNS
 * cutover (Phase 3). Each firing invokes the matching /api/cron/* route
 * in-process with the CRON_SECRET bearer token — mirroring vercel.json. The
 * `daily` route fans out to its child jobs internally, unchanged.
 */
// @ts-expect-error - generated by `opennextjs-cloudflare build`
import openNextWorker from "./.open-next/worker.js";

// @ts-expect-error - generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

type Env = {
  CRON_SECRET?: string;
  NEXT_PUBLIC_SITE_URL?: string;
};

/** Cloudflare cron expression -> internal cron route (mirrors vercel.json crons). */
const CRON_ROUTES: Record<string, string> = {
  "0 6 * * *": "/api/cron/daily",
  // Cloudflare's cron parser rejects "0" as Sunday (400 "invalid cron string"),
  // so this schedule is registered as "SUN" — the key must match what Cloudflare
  // passes back in controller.cron at runtime.
  "0 3 * * SUN": "/api/cron/check-live-urls",
  "0 4 * * *": "/api/cron/quality-rescore",
  "30 5 * * *": "/api/cron/verify-backfill",
  "0 15 * * 1,2": "/api/cron/weekly-digest",
};

const handler = openNextWorker as {
  fetch(request: Request, env: unknown, ctx: unknown): Promise<Response>;
};

export default {
  fetch(request: Request, env: Env, ctx: unknown): Promise<Response> {
    // apex -> www 301 redirect (replaces the vercel.json host redirect at cutover).
    const url = new URL(request.url);
    if (url.hostname === "vibetalent.work") {
      return Promise.resolve(
        Response.redirect(`https://www.vibetalent.work${url.pathname}${url.search}`, 301),
      );
    }
    return handler.fetch(request, env, ctx);
  },

  async scheduled(
    controller: { cron: string; scheduledTime: number },
    env: Env,
    ctx: unknown,
  ): Promise<void> {
    const route = CRON_ROUTES[controller.cron];
    if (!route) {
      console.error(`[cron] no route mapped for schedule "${controller.cron}"`);
      return;
    }
    const base = env.NEXT_PUBLIC_SITE_URL || "https://www.vibetalent.work";
    const request = new Request(new URL(route, base), {
      headers: { authorization: `Bearer ${env.CRON_SECRET ?? ""}` },
    });
    const response = await handler.fetch(request, env, ctx);
    if (!response.ok) {
      console.error(`[cron] ${route} responded ${response.status}`);
    }
  },
};
